# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_picture', models.ImageField(blank=True, upload_to='posts/')),
                ('post_name', models.CharField(max_length=200)),
                ('post_description', models.TextField()),
                ('date_posted', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-id']},
        ),
    ]
