# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0002_auto_20190530_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_department', models.IntegerField(default=0)),
                ('police_department', models.IntegerField(default=0)),
                ('hood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood_app.Neighborhood')),
            ],
        ),
    ]
