# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0003_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='health_department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='police_department',
            field=models.CharField(max_length=200),
        ),
    ]
