# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0004_auto_20190531_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood_app.Neighborhood'),
        ),
    ]
