# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood_app', '0005_post_hood_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
